/* Coordinate convention: UI dimensions are cm above/along the z=0 desktop;
   physics modules convert them to metres. D is horizontal ear→speaker range,
   never the y/forward component (which is D cos theta). */
(function(){
  'use strict';const P=window.DeskPhysics,{geometry:G,models:M,viz:V,plots:Plots}=P;
  const defaults={model:'kirchhoff',h_ear:48,h_woofer:29.5,h_tweeter:44,D:120,theta:30,tilt:0,desk_near:30,desk_far:70,desk_width:160,absorber_on:false,absorber_near:30,absorber_far:64,absorber_thickness:4,absorber_sigma:10000,c:343,rigid_R:.97,piston_radius:6.5,directivity:'piston',gridStep:.02,smoothing:0,two_way:false,coaxial:false,crossover:2000,crossover_order:4,band_lo:300,band_hi:3000};
  let state={...defaults},result=null,timeResult=null,ghost=null,pending=0,sweepResult=null;
  const $=id=>document.getElementById(id), fmt=(v,n=1)=>Number(v).toFixed(n), debounce=(fn,ms)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
  const specs={
    h_ear:['Ear height',20,80,.5,'cm'],h_woofer:['Woofer height',-20,80,.5,'cm'],h_tweeter:['Tweeter height',-20,90,.5,'cm'],D:['Listening distance D',60,250,1,'cm'],theta:['Triangle half-angle',10,45,.5,'°'],tilt:['Cabinet tilt',-20,20,.5,'°'],desk_near:['Desk near edge',0,60,1,'cm'],desk_far:['Desk far edge',20,120,1,'cm'],desk_width:['Desk width',40,300,2,'cm'],
    absorber_near:['Patch near edge',0,100,1,'cm'],absorber_far:['Patch far edge',5,120,1,'cm'],absorber_thickness:['Patch thickness',1,15,.5,'cm'],absorber_sigma:['Flow resistivity',3000,60000,500,'Pa·s/m²'],rigid_R:['Bare desk R',0,1,.01,''],piston_radius:['Piston radius',2,15,.5,'cm'],c:['Speed of sound',330,350,.5,'m/s'],crossover:['LR crossover',500,5000,50,'Hz'],crossover_order:['Crossover order',2,8,2,''],band_lo:['Comb band low',100,2000,50,'Hz'],band_hi:['Comb band high',500,10000,100,'Hz']
  };
  function control(name){const [label,min,max,step,unit]=specs[name],wrap=document.createElement('div');wrap.className='param';wrap.innerHTML=`<div class="param-head"><label for="${name}_range">${label} <span class="unit">${unit}</span></label><input id="${name}_number" type="number" min="${min}" max="${max}" step="${step}" value="${state[name]}"></div><input id="${name}_range" type="range" min="${min}" max="${max}" step="${step}" value="${state[name]}">`;
    const range=wrap.querySelector('input[type=range]'),num=wrap.querySelector('input[type=number]');
    const change=e=>{let v=Number(e.target.value);if(!Number.isFinite(v))return;v=Math.max(min,Math.min(max,v));state[name]=v;enforce();syncControls();updateGeometryOnly();schedule();};range.addEventListener('input',change);num.addEventListener('input',change);return wrap;
  }
  function mountControls(){
    ['h_ear','h_woofer','h_tweeter','D','theta','tilt','desk_near','desk_far','desk_width'].forEach(n=>$('geometryControls').append(control(n)));
    ['absorber_near','absorber_far','absorber_thickness','absorber_sigma'].forEach(n=>$('absorberControls').append(control(n)));
    ['rigid_R','piston_radius'].forEach(n=>$('sourceControls').append(control(n)));
    ['crossover','crossover_order'].forEach(n=>$('twoWayControls').append(control(n)));
    ['c','band_lo','band_hi'].forEach(n=>$('analysisControls').append(control(n)));
  }
  function syncControls(){for(const n of Object.keys(specs)){const r=$(n+'_range'),q=$(n+'_number');if(r){r.value=state[n];q.value=state[n]}}$('absorber_on').checked=state.absorber_on;$('two_way').checked=state.two_way;$('coaxial').checked=state.coaxial;$('directivity').value=state.directivity;$('gridStep').value=String(state.gridStep);$('smoothing').value=String(state.smoothing);document.querySelectorAll('[data-model]').forEach(b=>b.classList.toggle('active',b.dataset.model===state.model));updateVisibility()}
  function updateVisibility(){$('absorberControls').style.opacity=state.absorber_on?'1':'.42';$('twoWayControls').style.opacity=state.two_way?'1':'.42';$('coaxial').disabled=!state.two_way;$('polarFigure').style.display=state.two_way?'block':'none'}
  function enforce(){if(state.desk_near>state.desk_far)state.desk_far=state.desk_near;if(state.absorber_near>state.absorber_far)state.absorber_far=state.absorber_near;if(state.band_lo>state.band_hi)state.band_hi=state.band_lo;}
  function vizFrequency(){return Math.pow(10,Number($('viz_frequency').value))}
  function updateGeometryOnly(){
    const f=vizFrequency();$('viz_frequency_out').textContent=f>=1000?`${(f/1000).toFixed(2)} kHz`:`${f.toFixed(0)} Hz`;V.drawPlan($('planCanvas'),state,f);V.drawElevation($('elevationCanvas'),state,f);updateHeadline(result);
  }
  function updateHeadline(res){const g=G.solve(state),notches=[1,2,3].map(n=>g.notch(n));$('bounceReadout').textContent=`${fmt(g.bounce.y*100)} fwd · ${fmt(g.bounce.x*100)} lat`;$('deltaReadout').textContent=`${fmt(g.delta*100,2)} cm`;$('notchReadout').textContent=notches[0]>=1000?`${fmt(notches[0]/1000,2)} kHz`:`${fmt(notches[0],0)} Hz`;$('grazingReadout').textContent=`${fmt(g.grazing*180/Math.PI)}° · edge ${g.edge>=0?'+':''}${fmt(g.edge*100)} cm`;
    if(res){const comb=M.combDepth(res.frequencies,res.db,state.band_lo,state.band_hi);$('combReadout').textContent=`${fmt(comb.swing)} dB`}
    const status=$('status');if(state.model==='specular'&&!g.onDesk){status.className='status warn';status.textContent='Specular bounce misses the desktop. This point model contains no edge/fringe contribution; switch to Fresnel or Kirchhoff.'}else{status.className='status';status.textContent=`Bounce is ${g.onDesk?'on':'off'} the desktop. Notches: ${notches.map(x=>x>=1000?fmt(x/1000,2)+' kHz':fmt(x,0)+' Hz').join(' · ')}.`}
  }
  function plotAll(){if(!result)return;const C=Plots.colors(),smooth=M.smoothLog(result.frequencies,result.db,state.smoothing),series=[{x:result.frequencies,y:smooth,color:C.cyan,label:'Current'}];if(ghost)series.push({x:ghost.result.frequencies,y:M.smoothLog(ghost.result.frequencies,ghost.result.db,state.smoothing),color:C.amber,label:'Frozen',dash:[5,4],alpha:.85});Plots.chart($('responsePlot'),series,{logx:true,xmin:20,xmax:20000,ymin:-36,ymax:12,zero:true});
    const cs=[{x:result.frequencies,y:Float64Array.from(result.coverage,x=>x*100),color:C.blue,label:'Current'}];if(ghost)cs.push({x:ghost.result.frequencies,y:Float64Array.from(ghost.result.coverage,x=>x*100),color:C.amber,label:'Frozen',dash:[5,4]});Plots.chart($('coveragePlot'),cs,{logx:true,xmin:20,xmax:20000,ymin:0,ymax:100});
    if(timeResult){const gs=[{x:timeResult.gdF,y:timeResult.gd,color:C.purple,label:'Current'}],es=[{x:timeResult.time,y:timeResult.etc,color:C.cyan,label:'Current'}];if(ghost?.time){gs.push({x:ghost.time.gdF,y:ghost.time.gd,color:C.amber,label:'Frozen',dash:[5,4]});es.push({x:ghost.time.time,y:ghost.time.etc,color:C.amber,label:'Frozen',dash:[5,4]})}Plots.chart($('gdPlot'),gs,{logx:true,xmin:80,xmax:10000,ymin:-20,ymax:20,zero:true});Plots.chart($('etcPlot'),es,{xmin:0,xmax:20,ymin:-70,ymax:3});}
    if(state.two_way)Plots.polar($('polarPlot'),M.verticalPolar(state));updateHeadline(result);
  }
  function calculate(model,withTime){const f=G.frequencyGrid(400);return {r:M.evaluate(state,f,model),t:withTime?M.timeAnalysis({...state,model}):null}}
  function compute(){const token=++pending;if(state.model==='kirchhoff'){
      const preview=calculate('fresnel',false);if(token!==pending)return;result=preview.r;updateHeadline(result);plotAll();$('status').textContent+=' Kirchhoff integral is updating…';
      setTimeout(()=>{if(token!==pending)return;const exact=calculate('kirchhoff',true);if(token!==pending)return;result=exact.r;timeResult=exact.t;const g=result.grid,waveStep=state.c/20000/6;$('qualityNote').textContent=`${g.n.toLocaleString()} elements · ${fmt(g.step*100,2)} cm cells. λ/6 at 20 kHz is ${fmt(waveStep*100,3)} cm; this bounded live grid is an engineering preview above ${fmt(state.c/(6*g.step)/1000,1)} kHz.`;plotAll();updateHeadline(result);updateGeometryOnly();},30);
    }else{const exact=calculate(state.model,true);if(token!==pending)return;result=exact.r;timeResult=exact.t;$('qualityNote').textContent=state.model==='fresnel'?'First-zone energy coverage is integrated from the same ellipse shown in plan.':'Point reflector; finite-edge diffraction is not represented.';plotAll();updateGeometryOnly();}}
  const schedule=debounce(compute,70);
  function applyPreset(name){state={...state,...({reference:{h_ear:48,h_woofer:29.5,h_tweeter:44,D:120,theta:30,tilt:0},lowered:{h_woofer:14.5,tilt:10},raised:{h_woofer:59.5,tilt:-8},ear:{h_woofer:48,tilt:0}}[name]||{})};syncControls();updateGeometryOnly();compute()}
  function freeze(){if(!result)return;ghost={state:{...state},result:{...result,frequencies:new Float64Array(result.frequencies),db:new Float64Array(result.db),coverage:new Float64Array(result.coverage)},time:timeResult?{gdF:new Float64Array(timeResult.gdF),gd:new Float64Array(timeResult.gd),time:new Float64Array(timeResult.time),etc:new Float64Array(timeResult.etc)}:null};$('freeze').textContent='Update frozen trace';plotAll()}
  function sweepMetrics(s){const g=G.solve(s),freq=G.frequencyGrid(84,200,5000),db=new Float64Array(freq.length),ph=new Float64Array(freq.length);for(let i=0;i<freq.length;i++){const f=freq[i],k=2*Math.PI*f/s.c,cov=G.coverage(s,g,f,18),a=s.rigid_R*Math.sqrt(cov.fraction)*g.direct/g.reflected,re=1+a*Math.cos(-k*g.delta),im=a*Math.sin(-k*g.delta);db[i]=20*Math.log10(Math.max(1e-6,Math.hypot(re,im)));ph[i]=Math.atan2(im,re)}const comb=M.combDepth(freq,db,s.band_lo,s.band_hi).swing;let gd=0;for(let i=1;i<freq.length-1;i++){let d=ph[i+1]-ph[i-1];while(d>Math.PI)d-=2*Math.PI;while(d<-Math.PI)d+=2*Math.PI;gd=Math.max(gd,Math.abs(-d/(2*Math.PI*(freq[i+1]-freq[i-1]))*1000));}return {comb,gd}}
  function runSweep(){const xKey=$('sweepX').value,yKey=$('sweepY').value,x0=Number($('sweepXMin').value),x1=Number($('sweepXMax').value),y0=Number($('sweepYMin').value),y1=Number($('sweepYMax').value),nx=15,ny=yKey==='none'?1:13,xs=Array.from({length:nx},(_,i)=>x0+(x1-x0)*i/(nx-1)),ys=Array.from({length:ny},(_,i)=>y0+(y1-y0)*(ny===1?0:i/(ny-1))),values=new Float64Array(nx*ny),rank=[];for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const s={...state,[xKey]:xs[i]};if(yKey!=='none')s[yKey]=ys[j];const m=sweepMetrics(s);values[j*nx+i]=m.comb;rank.push({i,j,x:xs[i],y:ys[j],...m})}rank.sort((a,b)=>(a.gd+.15*a.comb)-(b.gd+.15*b.comb));sweepResult={xs,ys,values,min:Math.min(...values),max:Math.max(...values),xLabel:specs[xKey][0],yLabel:yKey==='none'?'single row':specs[yKey][0],xKey,yKey,rank};Plots.heatmap($('heatmap'),sweepResult,loadCell);const body=$('ranking');body.innerHTML='';rank.slice(0,8).forEach((r,k)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${k+1}</td><td>${xKey} ${fmt(r.x)}${yKey==='none'?'':` · ${yKey} ${fmt(r.y)}`}</td><td>${fmt(r.comb)} dB</td><td>${fmt(r.gd)} ms</td>`;tr.onclick=()=>loadCell(r.i,r.j);body.append(tr)})}
  function loadCell(i,j){if(!sweepResult)return;state[sweepResult.xKey]=sweepResult.xs[i];if(sweepResult.yKey!=='none')state[sweepResult.yKey]=sweepResult.ys[j];syncControls();updateGeometryOnly();compute();window.scrollTo({top:0,behavior:'smooth'})}
  function bind(){
    $('preset').onchange=e=>applyPreset(e.target.value);$('freeze').onclick=freeze;$('reset').onclick=()=>{state={...defaults};$('preset').value='reference';ghost=null;$('freeze').textContent='Freeze A/B trace';syncControls();compute()};
    $('modelChoice').onclick=e=>{const m=e.target.dataset.model;if(!m)return;state.model=m;syncControls();compute()};
    for(const id of ['absorber_on','two_way','coaxial'])$(id).onchange=e=>{state[id]=e.target.checked;updateVisibility();updateGeometryOnly();schedule()};
    $('directivity').onchange=e=>{state.directivity=e.target.value;schedule()};$('smoothing').onchange=e=>{state.smoothing=Number(e.target.value);plotAll()};$('gridStep').onchange=e=>{state.gridStep=Number(e.target.value);schedule()};$('viz_frequency').oninput=updateGeometryOnly;$('runSweep').onclick=runSweep;
    window.addEventListener('resize',debounce(()=>{updateGeometryOnly();plotAll();if(sweepResult)Plots.heatmap($('heatmap'),sweepResult,loadCell)},100));matchMedia('(prefers-color-scheme: light)').addEventListener?.('change',()=>{updateGeometryOnly();plotAll()});
  }
  mountControls();bind();syncControls();updateGeometryOnly();compute();
})();
