/* Coordinate convention under test: x lateral, y forward, z above desktop;
   D is horizontal range and speaker y must equal D cos(theta), not D. */
(function(){
  'use strict';const {geometry:G,models:M}=DeskPhysics,$=id=>document.getElementById(id);let pass=0,fail=0,details=[];
  const base={model:'specular',h_ear:48,h_woofer:29.5,h_tweeter:44,D:120,theta:30,tilt:0,desk_near:30,desk_far:70,desk_width:160,absorber_on:false,absorber_near:30,absorber_far:64,absorber_thickness:4,absorber_sigma:10000,c:343,rigid_R:.97,piston_radius:6.5,directivity:'omni',gridStep:.01,smoothing:0,two_way:false,coaxial:false,crossover:2000,crossover_order:4,band_lo:300,band_hi:3000};
  const near=(a,b,t,msg)=>{if(Math.abs(a-b)>t)throw Error(`${msg}: got ${a}, expected ${b} ± ${t}`)};
  function test(name,fn){const li=document.createElement('li');try{fn();li.className='pass';li.textContent=`PASS · ${name}`;pass++}catch(e){li.className='fail';li.textContent=`FAIL · ${name}`;details.push(`${name}\n  ${e.message}`);fail++}$('results').append(li)}
  test('D is horizontal range; y = D cos θ',()=>{const g=G.solve(base);near(g.speaker.y,1.2*Math.cos(Math.PI/6),1e-12,'forward component');near(Math.hypot(g.speaker.x,g.speaker.y),1.2,1e-12,'horizontal range')});
  test('1. Ear-height symmetry',()=>{for(const D of [60,120,231]){const g=G.solve({...base,h_woofer:48,D});near(g.t,.5,1e-15,'t');near(g.bounce.x,g.speaker.x/2,1e-14,'x midpoint');near(g.bounce.y,g.speaker.y/2,1e-14,'y midpoint')}});
  test('2. Reference geometry',()=>{const g=G.solve(base);near(g.t,.61935,.0002,'t');near(g.bounce.y*100,64.36,.15,'forward');near(g.bounce.x*100,37.16,.15,'lateral');near(g.direct*100,121.42,.15,'direct');near(g.reflected*100,142.85,.15,'reflected');near(g.delta*100,21.43,.2,'delta');near(g.notch(1),800,12,'notch');near(g.grazing*180/Math.PI,32.85,.2,'grazing')});
  test('3. Empirical geometry back-prediction',()=>{const s={...base,h_ear:48,h_woofer:48,D:90,desk_near:-50,desk_far:180,desk_width:300},g=G.solve(s);near(g.delta*100,41.6,.2,'delta');near(g.notch(1),412,3,'notch');const f=Float64Array.from({length:240},(_,i)=>250+i*1.5),ev=M.evaluate(s,f,'specular');const ph=Array.from(ev.hre,(_,i)=>Math.atan2(ev.him[i],ev.hre[i]));let peak=0;for(let i=1;i<f.length-1;i++){let d=ph[i+1]-ph[i-1];while(d>Math.PI)d-=2*Math.PI;while(d<-Math.PI)d+=2*Math.PI;peak=Math.max(peak,Math.abs(-d/(2*Math.PI*(f[i+1]-f[i-1]))*1000))}if(peak<1.5)throw Error(`comb-delay excursion too small: ${peak.toFixed(2)} ms`)});
  test('4. Lowered config misses desk',()=>{const g=G.solve({...base,h_woofer:14.5});near(g.t,.768,.002,'t');near(g.bounce.y*100,79.8,.3,'forward');near(g.delta*100,10.7,.25,'delta');near(g.notch(1),1600,45,'notch');if(g.onDesk)throw Error('bounce should be off desk')});
  test('5. Raised config',()=>{const g=G.solve({...base,h_woofer:59.5});near(g.t,.447,.002,'t');near(g.bounce.y*100,46.4,.25,'forward');near(g.notch(1),423,6,'notch')});
  test('6. Far-edge crossing distance',()=>{const s={...base,D:131},g=G.solve(s);near(g.bounce.y*100,70,.35,'forward edge');const factor=g.bounce.y/(s.D*.01);near(factor,.536,.002,'forward reach / D')});
  test('7. Kirchhoff converges toward image-source result',()=>{const s={...base,desk_near:-200,desk_far:300,desk_width:500,gridStep:.01},fs=Float64Array.of(100,300,800,2000,5000),a=M.evaluate(s,fs,'specular'),b=M.evaluate(s,fs,'kirchhoff');for(let i=0;i<fs.length;i++)near(b.db[i],a.db[i],.55,`at ${fs[i]} Hz`)});
  test('8. Reciprocity of Δ, notches and omni |H|',()=>{const a={...base,desk_near:-100,desk_far:220,desk_width:400},b={...a,h_ear:a.h_woofer,h_woofer:a.h_ear},ga=G.solve(a),gb=G.solve(b);near(ga.delta,gb.delta,1e-14,'delta');near(ga.notch(2),gb.notch(2),1e-10,'notch');near(ga.t,1-gb.t,1e-14,'t complement');const fs=G.frequencyGrid(80,100,5000),ha=M.evaluate(a,fs,'specular'),hb=M.evaluate(b,fs,'specular');for(let i=0;i<fs.length;i++)near(ha.db[i],hb.db[i],1e-9,`|H| ${fs[i]} Hz`)});
  test('9. Omni rigid large desk gives classic deep two-source comb',()=>{const s={...base,desk_near:-100,desk_far:220,desk_width:400,rigid_R:1},g=G.solve(s),f=g.notch(1),ev=M.evaluate(s,Float64Array.of(f),'specular'),expected=20*Math.log10((s.D*.01)*Math.abs(1/g.direct-1/g.reflected));near(ev.db[0],expected,.02,'path-loss limited notch');if(ev.db[0]>-8)throw Error('notch is unexpectedly shallow')});
  $('summary').innerHTML=`<strong>${pass} passed · ${fail} failed</strong><br><span class="microcopy">c = 343 m/s. Open this page directly from disk; no runner is required.</span>`;$('summary').classList.add(fail?'fail':'pass');$('details').textContent=details.join('\n\n');
})();
