/* Plot rendering has no geometry of its own; x/y/z conventions remain owned by
   the physics modules. Canvas coordinates are screen pixels only. */
(function(root){
  'use strict';const ns=root.DeskPhysics=root.DeskPhysics||{};
  function setup(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(280,Math.round(r.width)),h=Math.max(180,Math.round(r.height));if(canvas.width!==w*d||canvas.height!==h*d){canvas.width=w*d;canvas.height=h*d;}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);return {c,w,h};}
  function colors(){const q=getComputedStyle(document.documentElement);return {bg:q.getPropertyValue('--bg').trim(),panel:q.getPropertyValue('--panel').trim(),line:q.getPropertyValue('--line').trim(),text:q.getPropertyValue('--text').trim(),muted:q.getPropertyValue('--muted').trim(),cyan:q.getPropertyValue('--cyan').trim(),amber:q.getPropertyValue('--amber').trim(),blue:q.getPropertyValue('--blue').trim(),purple:q.getPropertyValue('--purple').trim(),red:q.getPropertyValue('--red').trim()};}
  function mix(a,b,t){const hex=x=>{const s=x.trim().replace('#','');if(s.length!==6)return [80,160,160];return [0,2,4].map(i=>parseInt(s.slice(i,i+2),16))},A=hex(a),B=hex(b),v=A.map((x,i)=>Math.round(x+(B[i]-x)*t));return `rgb(${v[0]},${v[1]},${v[2]})`}
  function nice(v){if(Math.abs(v)>=1000)return `${(v/1000).toFixed(v>=10000?0:1)}k`;if(Math.abs(v)<1&&v!==0)return v.toFixed(2);return v.toFixed(Math.abs(v)<10?1:0)}
  function chart(canvas,series,opt={}){
    const {c,w,h}=setup(canvas),C=colors(),p={l:48,r:14,t:10,b:28};c.clearRect(0,0,w,h);
    const all=series.filter(x=>x&&x.x&&x.x.length),xmin=opt.xmin??Math.min(...all.map(s=>s.x[0])),xmax=opt.xmax??Math.max(...all.map(s=>s.x[s.x.length-1]));let ymin=opt.ymin,ymax=opt.ymax;if(ymin==null||ymax==null){let lo=Infinity,hi=-Infinity;for(const s of all)for(let i=0;i<s.y.length;i++)if(s.x[i]>=xmin&&s.x[i]<=xmax&&Number.isFinite(s.y[i])){lo=Math.min(lo,s.y[i]);hi=Math.max(hi,s.y[i]);}const m=Math.max(1,(hi-lo)*.08);ymin=ymin??lo-m;ymax=ymax??hi+m;}
    const X=x=>p.l+(opt.logx?(Math.log(x)-Math.log(xmin))/(Math.log(xmax)-Math.log(xmin)):(x-xmin)/(xmax-xmin))*(w-p.l-p.r),Y=y=>p.t+(ymax-y)/(ymax-ymin)*(h-p.t-p.b);
    c.font='10px system-ui';c.strokeStyle=C.line;c.fillStyle=C.muted;c.lineWidth=1;
    const yt=5;for(let i=0;i<=yt;i++){const y=ymin+(ymax-ymin)*i/yt,py=Y(y);c.beginPath();c.moveTo(p.l,py);c.lineTo(w-p.r,py);c.stroke();c.fillText(nice(y),3,py+3)}
    const ticks=opt.logx?[20,50,100,200,500,1000,2000,5000,10000,20000].filter(x=>x>=xmin&&x<=xmax):Array.from({length:6},(_,i)=>xmin+(xmax-xmin)*i/5);for(const x of ticks){const px=X(x);c.beginPath();c.moveTo(px,p.t);c.lineTo(px,h-p.b);c.stroke();const lab=nice(x),tw=c.measureText(lab).width;c.fillText(lab,Math.max(p.l,Math.min(w-p.r-tw,px-tw/2)),h-9)}
    c.save();c.beginPath();c.rect(p.l,p.t,w-p.l-p.r,h-p.t-p.b);c.clip();for(const s of all){c.beginPath();c.strokeStyle=s.color||C.cyan;c.globalAlpha=s.alpha??1;c.lineWidth=s.width||1.7;c.setLineDash(s.dash||[]);let begun=false;for(let i=0;i<s.x.length;i++){const x=s.x[i],y=s.y[i];if(x<xmin||x>xmax||!Number.isFinite(y))continue;const px=X(x),py=Y(Math.max(ymin,Math.min(ymax,y)));if(!begun){c.moveTo(px,py);begun=true}else c.lineTo(px,py)}c.stroke()}c.restore();c.globalAlpha=1;c.setLineDash([]);
    if(opt.zero&&ymin<0&&ymax>0){c.strokeStyle=C.muted;c.setLineDash([3,4]);c.beginPath();c.moveTo(p.l,Y(0));c.lineTo(w-p.r,Y(0));c.stroke();c.setLineDash([])}
    if(series.length>1){let x=p.l+8;for(const s of all){c.strokeStyle=s.color||C.cyan;c.lineWidth=2;c.beginPath();c.moveTo(x,p.t+8);c.lineTo(x+16,p.t+8);c.stroke();c.fillStyle=C.muted;c.fillText(s.label||'',x+21,p.t+11);x+=38+c.measureText(s.label||'').width}}
    canvas._plot={series:all,opt,X,Y,bounds:p,C};
  }
  function polar(canvas,data){const {c,w,h}=setup(canvas),C=colors();c.clearRect(0,0,w,h);const cx=w/2,cy=h-22,r=Math.min(w*.43,h*.77);c.strokeStyle=C.line;c.fillStyle=C.muted;c.font='10px system-ui';for(const db of [0,-6,-12,-18,-24]){const rr=r*(1+db/30);c.beginPath();c.arc(cx,cy,rr,Math.PI,2*Math.PI);c.stroke();c.fillText(`${db}`,cx+3,cy-rr+11)}for(const a of [-60,-30,0,30,60]){const t=(a-90)*Math.PI/180;line(cx,cy,cx+r*Math.cos(t),cy+r*Math.sin(t));c.fillText(`${a}°`,cx+r*Math.cos(t)-8,cy+r*Math.sin(t)-3)}c.strokeStyle=C.purple;c.lineWidth=2;c.beginPath();for(let i=0;i<data.angles.length;i++){const t=(data.angles[i]-90)*Math.PI/180,rr=r*Math.max(0,1+Math.max(-30,data.db[i])/30),x=cx+rr*Math.cos(t),y=cy+rr*Math.sin(t);i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();function line(x1,y1,x2,y2){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()}}
  function heatmap(canvas,result,onPick){const {c,w,h}=setup(canvas),C=colors(),p={l:52,r:14,t:14,b:36},cols=result.xs.length,rows=result.ys.length,cw=(w-p.l-p.r)/cols,ch=(h-p.t-p.b)/rows,min=result.min,max=result.max;c.clearRect(0,0,w,h);for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const v=result.values[j*cols+i],t=(v-min)/(max-min||1);c.fillStyle=mix(C.cyan,C.red,t);c.fillRect(p.l+i*cw,p.t+(rows-1-j)*ch,cw+.5,ch+.5)}c.fillStyle=C.muted;c.font='10px system-ui';for(let i=0;i<cols;i+=Math.max(1,Math.floor(cols/5))){const x=p.l+(i+.5)*cw;c.fillText(nice(result.xs[i]),x-9,h-12)}for(let j=0;j<rows;j+=Math.max(1,Math.floor(rows/5))){const y=p.t+(rows-j-.5)*ch;c.fillText(nice(result.ys[j]),4,y+3)}c.fillText(result.xLabel,p.l,h-1);c.save();c.translate(10,h/2+20);c.rotate(-Math.PI/2);c.fillText(result.yLabel,0,0);c.restore();canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),i=Math.floor((e.clientX-r.left-p.l)/cw),jj=Math.floor((e.clientY-r.top-p.t)/ch),j=rows-1-jj;if(i>=0&&i<cols&&j>=0&&j<rows)onPick(i,j)}}
  ns.plots={chart,polar,heatmap,colors};
})(window);
